version: '3.4'

x-environment: &common-vars
    MYSQL_PASSWORD: 
    MYSQL_DATABASE: 
    MYSQL_USER: 
    MYSQL_ROOT_PASSWORD: 
    TZ: Europe/Rome
    UPLOAD_MAX_SIZE: 20G

services:
  db:
    image: mariadb:10
    deploy:
      replicas: 1    
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      << : *common-vars

  app:
    image: nextcloud:16-fpm
    deploy:
      replicas: 1    
    restart: always
    volumes:
      - nc_html:/var/www/html
      - nc_data:/var/www/html/data
      - nc_apps:/var/www/html/apps
      - nc_config:/var/www/html/config
      - /srv/data/docker/containers/nextcloud-app/redis.config.php:/usr/src/nextcloud/config/redis.config.php
    environment:
      << : *common-vars
      MYSQL_HOST : db
    depends_on:
      - db
      - redis

  web:
    image: nginx:1.17
    deploy:
      replicas: 1    
    restart: always
    environment:
      TZ: Europe/Rome    
    ports:
      - 8080:80
    volumes:
      - nc_html:/var/www/html:ro
      - /srv/data/docker/containers/nextcloud-app/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nc_data:/var/www/html/data
      - nc_apps:/var/www/html/apps
      - nc_config:/var/www/html/config
      - /srv/data/docker/containers/nextcloud-app/redis.config.php:/usr/src/nextcloud/config/redis.config.php
    depends_on:
      - app

  cron:
    image: nextcloud:16-fpm
    deploy:
      replicas: 1    
    restart: always
    environment:
      TZ: Europe/Rome    
    volumes:
      - nc_html:/var/www/html:ro
      - nc_data:/var/www/html/data
      - nc_apps:/var/www/html/apps
      - nc_config:/var/www/html/config
      - /srv/data/docker/containers/nextcloud-app/redis.config.php:/usr/src/nextcloud/config/redis.config.php
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  onlyoffice:
    image: onlyoffice/documentserver:latest
    deploy:
      replicas: 1    
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 8081:80
      - 8443:443
    depends_on:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      << : *common-vars    
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - '8280:80'
    depends_on:
      - db

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/docker/containers/nextcloud-app/mariadb/db
  nc_html:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/docker/containers/nextcloud-app/nextcloud/html
  nc_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/docker/containers/nextcloud-app/nextcloud/data
  nc_apps:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/docker/containers/nextcloud-app/nextcloud/apps
  nc_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /srv/data/docker/containers/nextcloud-app/nextcloud/config
