version: '3.4'

x-environment: &common-vars
    MYSQL_PASSWORD: KeepYourPasswordVerySecure967
    MYSQL_DATABASE: nextcloud
    MYSQL_USER: nextcloud
    MYSQL_ROOT_PASSWORD: UseAveryStrongPassword4490

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /srv/data/docker/containers/nextcloud-app/mariadb/db:/var/lib/mysql
    environment:
      << : *common-vars

  redis:
    image: redis
    restart: always

  app:
    image: nextcloud:fpm
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - /srv/data/docker/containers/nextcloud-app/nextcloud/data:/var/www/html/data
      - /srv/data/docker/containers/nextcloud-app/nextcloud/apps:/var/www/html/apps
      - /srv/data/docker/containers/nextcloud-app/nextcloud/config:/var/www/html/config
      - /srv/data/docker/containers/nextcloud-app/redis.config.php:/usr/src/nextcloud/config/redis.config.php
    environment:
      << : *common-vars
      MYSQL_HOST : db
    depends_on:
      - db
      - redis

  web:
    image: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - /srv/data/docker/containers/nextcloud-app/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nextcloud:/var/www/html:ro
    depends_on:
      - app

  cron:
    image: nextcloud:fpm
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

  onlyoffice:
    image: onlyoffice/documentserver:latest
    stdin_open: true
    tty: true
    restart: always
    ports:
      - 8081:80
      - 8443:443
    volumes:
      - onlyoffice_data:/var/www/onlyoffice/Data
      - onlyoffice_log:/var/log/onlyoffice

volumes:
  nextcloud:
  onlyoffice_data:
  onlyoffice_log:
