version: '3.4'

x-environment: &common-vars
    MYSQL_PASSWORD: KeepYourPasswordVerySecure967
    MYSQL_DATABASE: nextcloud
    MYSQL_USER: nextcloud
    MYSQL_ROOT_PASSWORD: UseAveryStrongPassword4490

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      << : *common-vars

  redis:
    image: redis
    restart: always

  app:
    image: nextcloud:fpm
    restart: always
    volumes:
      - /srv/docker/containers/nextcloud-app/redis.config.php:/usr/src/nextcloud/config/redis.config.php
      - nextcloud:/var/www/html
    environment:
      << : *common-vars
      MYSQL_HOST : db
    depends_on:
      - db
      - redis

  web:
    image: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - /srv/docker/containers/nextcloud-app/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nextcloud:/var/www/html:ro
    depends_on:
      - app

  cron:
    image: nextcloud:fpm
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:
