# STACK_BASE_PATH [base folder where to host files, must exists]
# STACK_BASE_PATH=/srv/data/docker/containers/nextcloud-app ; grep device docker-compose.yml|grep -v "#"|awk '{print $2}'|while read dir; do eval mkdir -p $dir; done

version: '3.7'

x-environment: &common-vars
    MYSQL_PASSWORD: 
    MYSQL_DATABASE: 
    MYSQL_USER: 
    MYSQL_ROOT_PASSWORD: 
    UPLOAD_MAX_SIZE: 20G

x-vol-tz: &v-tz /etc/timezone:/etc/timezone:ro
x-vol-ltime: &v-ltime /etc/localtime:/etc/localtime:ro
x-vol-lgen: &v-lgen /etc/locale.gen:/etc/locale.gen:ro
x-vols: &vols
  - *v-tz
  - *v-ltime
  - *v-lgen

services:
  db:
    image: mariadb:10
    hostname: db
    deploy:
      replicas: 1    
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - *v-tz
      - *v-ltime
      - *v-lgen
      - db:/var/lib/mysql
    environment:
      << : *common-vars

  app:
    image: nextcloud:18-fpm
    hostname: nc
    deploy:
      replicas: 1    
    restart: always
    volumes:
      - *v-tz
      - *v-ltime
      - *v-lgen
      - nc_html:/var/www/html
      - nc_data:/var/www/html/data
      - nc_apps:/var/www/html/custom_apps
      - nc_config:/var/www/html/config
    environment:
      << : *common-vars
      MYSQL_HOST : db
    depends_on:
      - db

  web:
    image: nginx:1.17
    hostname: nginx
    deploy:
      replicas: 1    
    restart: always
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - *v-tz
      - *v-ltime
      - *v-lgen
      - nc_html:/var/www/html:ro
      - ${STACK_BASE_PATH}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nc_data:/var/www/html/data
      - nc_apps:/var/www/html/custom_apps
      - nc_config:/var/www/html/config
    depends_on:
      - app

  cron:
    image: nextcloud:18-fpm
    hostname: nc-cron
    deploy:
      replicas: 1    
    restart: always
    volumes:
      - *v-tz
      - *v-ltime
      - *v-lgen
      - nc_html:/var/www/html
      - nc_data:/var/www/html/data
      - nc_apps:/var/www/html/custom_apps
      - nc_config:/var/www/html/config
    entrypoint: /cron.sh
    depends_on:
      - db

  onlyoffice:
    image: onlyoffice/documentserver:latest
    hostname: oo
    deploy:
      replicas: 1    
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - *v-tz
      - *v-ltime
      - *v-lgen
      - oo_data:/var/www/onlyoffice/Data
      - oo_pg:/var/lib/postgresql
      - oo_rabbit:/var/lib/rabbitmq
      - oo_redis:/var/lib/redis
    ports:
      - 8081:80
      - 8443:443
    depends_on:
      - app

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    hostname: pma
    environment:
      << : *common-vars    
      PMA_HOST: db
      PMA_PORT: 3306
    volumes: *vols
    ports:
      - '8280:80'
    depends_on:
      - db

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STACK_BASE_PATH}/mariadb/db
  nc_html:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STACK_BASE_PATH}/nextcloud/html
  nc_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STACK_BASE_PATH}/nextcloud/data
  nc_apps:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STACK_BASE_PATH}/nextcloud/apps
  nc_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STACK_BASE_PATH}/nextcloud/config
  oo_logs:
  oo_lib:
  oo_fonts:
  oo_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STACK_BASE_PATH}/onlyoffice/data
  oo_pg:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STACK_BASE_PATH}/onlyoffice/postgresql/db
  oo_rabbit:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STACK_BASE_PATH}/onlyoffice/rabbitmq/db
  oo_redis:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${STACK_BASE_PATH}/onlyoffice/redis/data
